name: Bug Report
description: This is a template for reporting bugs
title: "BUG: Short description of bug"
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        ### New Bug Report

        This template is used to report issues, errors, or otherwise incorrect behavior present in this project. Before starting a new bug report, please check the Issues list to ensure that another user has not already reported your bug.
  - type: checkboxes
    attributes:
      label: Have you updated the title?
      description: Please provide a short description of the bug in the "Title" field above. Be sure to keep the `BUG:` tag.
      options:
        - label: I have updated the issue's title.
          required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the bug.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Tell us what should happen.
    validations:
      required: true
  - type: textarea
    id: observed
    attributes:
      label: Current / Observed Behavior
      description: Tell us what happens instead of the expected behavior.
    validations:
      required: true
  - type: textarea
    id: stepsToReproduce
    attributes:
      label: Steps to Reproduce
      description: Provide a link to a live example or an unambiguous set of steps to reproduce this bug. Include any relevant code or screenshots, if applicable.
      value: |
        1.
        2.
        3.
        4.
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Browser / Platform Info
      description: What browser version and operating system (OS) are you using?
      placeholder: e.g. Chrome 103 on Windows 10
